name: login
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  shared_preferences: ^2.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  flutter_screenutil: ^5.5.4
  google_sign_in: ^5.2.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

