// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmYmmeYMKNeKIg9q-RYc_FzGm_eHT3ns',
    appId: '1:235976040251:web:f836a80847aef8f0f3a11e',
    messagingSenderId: '235976040251',
    projectId: 'miniproject-33104',
    authDomain: 'miniproject-33104.firebaseapp.com',
    storageBucket: 'miniproject-33104.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmeoYyVnoOyBAwBSh8Rhmczmh-rMsYXM',
    appId: '1:235976040251:android:f15584fb501a5918f3a11e',
    messagingSenderId: '235976040251',
    projectId: 'miniproject-33104',
    storageBucket: 'miniproject-33104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDWrmmwi97Rm-Q6dDsTYvn6WEyfj-8Ac',
    appId: '1:235976040251:ios:5f9bc31dea3bb689f3a11e',
    messagingSenderId: '235976040251',
    projectId: 'miniproject-33104',
    storageBucket: 'miniproject-33104.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDWrmmwi97Rm-Q6dDsTYvn6WEyfj-8Ac',
    appId: '1:235976040251:ios:5f9bc31dea3bb689f3a11e',
    messagingSenderId: '235976040251',
    projectId: 'miniproject-33104',
    storageBucket: 'miniproject-33104.appspot.com',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApmYmmeYMKNeKIg9q-RYc_FzGm_eHT3ns',
    appId: '1:235976040251:web:489f69c800edcbe0f3a11e',
    messagingSenderId: '235976040251',
    projectId: 'miniproject-33104',
    authDomain: 'miniproject-33104.firebaseapp.com',
    storageBucket: 'miniproject-33104.appspot.com',
  );
}
